### ISSUE TITLE
Library "behavior_manager" cannot found

### ISSUE THREAD

**Issue by ziji-wu** [fnivek/bt-espresso#1]
I am pretty interested in your work "Learning Behavior Trees From Demonstration", and I met some trouble when I try to run this code.
My environment is as follows:
    Ubuntu 20.04 LTS
    Python 3.7
    ROS 2

However, I cannot find this python package named "behavior_manager", which mainly occurred in the python file "action_builders.py", I searched a lot on the internet, it is not a ROS interface, nor a general python package.
So,  could you please tell me how to set the running environment and what the "behavior_manager" is?

**Comment by fnivek** [comment]
I believe the behavior_manager is part of another one of my repositories that I haven't released. That package implements behaviors for a Fetch Robotics robot. Unfortunately, I no longer have access to those repositories. You'll want to just strip out the parts of this repository that are useful to you and adapt it for your use.

**Comment by ziji-wu** [comment]
Okay, I will have a try. Thanks a lot for your answer.

**Comment by ziji-wu** [comment]
Sorry to be a bother again. I still have some questions could you please give me the answer. 
I noticed that Python 2. x was used in this code, which means the ROS version is not ROS2, which only support Python 3.5+, however, I cannot know the exact ROS version, Lunar? Kinetic? or other older versions? Besides, could you still remember what additional dependencies must be satisfied to run this code?
Thanks a lot if you can solve the trouble I met.

**Comment by fnivek** [comment]
Pretty sure I was on Melodic when I wrote this.

**Comment by fnivek** [comment]
As for dependencies typically you'd have them listed somewhere but it seems I did not, which unfortunately means you'll need to take a look through the Python imports. I think I used scipy as a big one though.

**Comment by ziji-wu** [comment]
Got it, thanks a lot for your answer. Hoping for further cooperation in the future.
